name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: "env to deploy to"
        type: environment
        required: true 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event that triggered the workflow: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repo
        run: |
          echo the repository ${{ github.repository }} contains:
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "Testing..."
      
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "step 1"
          sleep 5
      - run: |
          echo "step 2"
          sleep 5
      - run: |
          echo "step 3"
          sleep 5
      - run: |
          echo "step 4"
          sleep 5
      - run: |
          echo "step 5"
          sleep 5
